// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFEQrYiWq5qV6AOq8aHcgkqq-Wz8f7ZDg',
    appId: '1:458236514278:android:60467cf28a957f1914d027',
    messagingSenderId: '458236514278',
    projectId: 'fwitch-8e933',
    storageBucket: 'fwitch-8e933.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM4iVOmmhPwHys3-E83YHYKRqLusroBqc',
    appId: '1:458236514278:ios:685bb4bd16ad46c914d027',
    messagingSenderId: '458236514278',
    projectId: 'fwitch-8e933',
    storageBucket: 'fwitch-8e933.appspot.com',
    androidClientId: '458236514278-khv9jpo8c136nl0amthisqp4bskdanl8.apps.googleusercontent.com',
    iosClientId: '458236514278-dqou6bl86p82nst5vlcoc8krletplnu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.fwitch',
  );
}
